name: Node.js Package

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn publish --non-interaction
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  
